version: '3.8'

services:
  planning-poker-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:mongo1

  mongo1:
    image: mongo:latest
    hostname: mongo1
    container_name: localmongo1
    restart: unless-stopped
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    ports:
      - '27017:27017'

  mongo2:
    image: mongo:latest
    hostname: mongo2
    container_name: localmongo2
    restart: unless-stopped
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    ports:
      - '27018:27017'
