-- +goose Up
ALTER TABLE games ADD created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE players ADD created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- +goose Down
ALTER TABLE games DROP COLUMN created_at;
ALTER TABLE players DROP COLUMN created_at;