name: Deploy and Build to Azure
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

env:
  IMAGE_PATH_WITH_TAG: ${{secrets.ACR_SERVER}}/planningpoker:${{github.sha}}

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
          dir: ./planning-poker-client

      - name: Build production client
        uses: borales/actions-yarn@v4
        with:
          cmd: build:prod
          dir: ./planning-poker-client
      
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: 'Run az commands'
        run: |
          az account show
          az group list
          az acr login -n ${{secrets.ACR_SERVER}}

      - name: 'Docker Build & Push to ACR'
        run: |
          docker build -f docker/dockerfile -t planningpokerapi planning-poker-api
          docker tag planningpokerapi ${{env.IMAGE_PATH_WITH_TAG}}
          docker push ${{env.IMAGE_PATH_WITH_TAG}}

      - name: 'Update container to point to new tag'
        run : |
          az webapp config container set --name -planning-poker-app --resource-group planning-poker --docker-custom-image-name '${{env.IMAGE_PATH_WITH_TAG}}'